Add definition of each field in data types in readme
bandprotocol/cw-band pull request #3
Opened 2022-11-08 08:11 UTC by RogerKSI

2022-11-23 07:35 UTC, colmazia reviewed
seems ok na

2022-11-30 07:52 UTC, taobun requested changes

2022-12-01 04:40 UTC, RogerKSI commented on docs/setup_relayer_hermes.md
> +You should find Hermes binary at hermes/target/debug/
fixed

2022-12-13 09:03 UTC, colmazia commented on contracts/price-feed/src/ibc.rs
> +    if let Some(version) = counterparty_version {
if counterparty_version is null, it will not throw error??

2022-12-13 09:36 UTC, colmazia commented on docs/how_to_request_data_from_bandchain_via_ibc.md
> +The oracle will send an acknowledgment message with the corresponding request_id on BandChain if the request can be processed so that the sender’s side can process the data as needed.
acknowledgment

2022-12-14 03:20 UTC, taobun approved these changes

2023-01-04 07:19 UTC, colmazia approved these changes

2023-01-04 07:20 UTC, colmazia commented
I prefer acknowledgement with 'e'

2023-01-05 04:28 UTC, merged