clarify cd-band docs
bandprotocol/cw-band pull request #8
Opened 2023-01-17 08:30 UTC by satawatnack

2023-01-17 09:43 UTC, RogerKSI approved these changes

2023-01-17 11:16 UTC, taobun requested changes

2023-01-17 11:42 UTC, RogerKSI commented on docs/contracts_price_feed.md
> +### Deploy contract
add build contract

2023-01-18 03:51 UTC, RogerKSI approved these changes

2023-01-18 04:24 UTC, taobun approved these changes

2023-01-18 04:24 UTC, merged